// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkk3KQM7IWReKd7fRo0quDcDs1pJKyDvI',
    appId: '1:337701429149:web:fc6212fa1e6a8d24ec5974',
    messagingSenderId: '337701429149',
    projectId: 'noteapp-cd885',
    authDomain: 'noteapp-cd885.firebaseapp.com',
    storageBucket: 'noteapp-cd885.firebasestorage.app',
    measurementId: 'G-FL2BENK0L2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9SgQkBtGPHzC24L5uEfwks9eSZ7n3P6c',
    appId: '1:337701429149:android:6afa7de90b660ecdec5974',
    messagingSenderId: '337701429149',
    projectId: 'noteapp-cd885',
    storageBucket: 'noteapp-cd885.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_CZUsVRdFQYwoXLOtEVW9jelCZJMXAfY',
    appId: '1:337701429149:ios:39ff3ab4660549c0ec5974',
    messagingSenderId: '337701429149',
    projectId: 'noteapp-cd885',
    storageBucket: 'noteapp-cd885.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_CZUsVRdFQYwoXLOtEVW9jelCZJMXAfY',
    appId: '1:337701429149:ios:39ff3ab4660549c0ec5974',
    messagingSenderId: '337701429149',
    projectId: 'noteapp-cd885',
    storageBucket: 'noteapp-cd885.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkk3KQM7IWReKd7fRo0quDcDs1pJKyDvI',
    appId: '1:337701429149:web:99d0e217295e189eec5974',
    messagingSenderId: '337701429149',
    projectId: 'noteapp-cd885',
    authDomain: 'noteapp-cd885.firebaseapp.com',
    storageBucket: 'noteapp-cd885.firebasestorage.app',
    measurementId: 'G-8TQCM76R4H',
  );
}
